<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOkJXJh8\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOkJXJh8/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOkJXJh8.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOkJXJh8\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOkJXJh8\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'OkJXJh8',
    'container.build_id' => '57937356',
    'container.build_time' => 1548927049,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerOkJXJh8');
